### ISSUE TITLE
Yellow border stays after snapping

### ISSUE THREAD

**Issue by pjmuller** [HendrikD/blockly-plugins#1]
Hi there Hendrik,

first of all, thank you for your type indicator plugin. Really helps to make blockly even more understable.
I'm just bumping into one problem. After snapping one block in. the blocks where it could have fitted in STAY yellow (see screenshots).

Any idea what could be the reason?

![momentum_podio_calculation__simplify_text](https://cloud.githubusercontent.com/assets/1681106/16179539/20392bf8-3669-11e6-99c9-819465bff4e8.png)

![momentum_podio_calculation__simplify_text](https://cloud.githubusercontent.com/assets/1681106/16179544/360e42e2-3669-11e6-952f-330a2f3c3924.png)

**Comment by HendrikD** [comment]
Hi pjmuller,

thank you for posting this issue. Since my own blockly project, that i developed the plugin for, is paused, i don't recognize when a new problem occures. So your feedback is very much appreciated. I will see if i can reproduce and fix your problem in the coming week.

Do you use the most recent blockly version? Since Blockly is in very active development, sometimes a patch breaks the type indicator and i need too make a little adjustment. This may be such an event.

Greetings

**Comment by pjmuller** [comment]
Hi Hendrik,

indeed I'm using the last blockly compressed (grabbed from the zipfile) on https://developers.google.com/blockly/guides/get-started/web 

Would be great if you could 'patch' it with this new version.

Greetings,
PJ

**Comment by HendrikD** [comment]
Hi pjmueller,

for me the type-indicator wasn't working at all with the newest blockly release. I think i fixed the problem in commit 0e7ef56 but could you check if the newest type-indicator works for you as well, so i can close this issue? Thank you.

Greetings.

**Comment by pjmuller** [comment]
Hi Hendrik, sorry for coming back to you on such a late notice.

Your changes did fix it. Super!

If it's ok I have 2 remaining questions
- in the gif on https://github.com/HendrikD/blockly-plugins/wiki/Type-Indicator the yellow border seems much ticker than in my installation. How can I change the size of the border?
- How did you create that gif? Which which tool? I would like to do the same :)

**Comment by HendrikD** [comment]
i'am in a hurry so just some short answeres:

1.: In the plugin .js file starting from line 176 there are the CSS styles. Change these to your needs:

// Add some styling to the type indicator
 Blockly.Css.CONTENT.push(
  '.blocklyTypeHighlightedConnectionPath {',
  '  fill: none;',
  '  stroke: #FC3;',
  '  stroke-width: 2px;',
    '  opacity: 1;',
  '}');

 // Change googles indicator color
 Blockly.Css.CONTENT.push(
  '.blocklyHighlightedConnectionPath {',
  '  stroke: #FC3;',
    '  stroke-width: 4px;',
    '  opacity: 1;',
  '}');

 // Add some styling to the occupied type indicator
 Blockly.Css.CONTENT.push(
  '.blocklyOccupiedTypeHighlightedConnectionPath {',
  '  fill: none;',
  '  stroke: #FC3;',
  '  stroke-width: 2px;',
  '  opacity: 1;',
'}');

2.: The tool for the gif Video is called GifCam and can be downlaoded from http://blog.bahraniapps.com/gifcam/

Greetings
